// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://zisqxkmgyrefjtcegdbu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inppc3F4a21neXJlZmp0Y2VnZGJ1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkzMzc2NDMsImV4cCI6MjA3NDkxMzY0M30.ZiohgM4octtW-d_e9SZoKmyAwP-MFenxw6Xntgwc58w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);